import { getSettings } from '../config';
import { getAgentVersion } from './version.service';
import type { ResolvedAgent, AgentConfig, AgentRule } from './agent-loader.service';
import { getToolReference } from './tools/config-schemas';

/**
 * Render a per-agent operations runbook as Markdown. The doc is derived
 * entirely from Clawndom's live state — parsed `clawndom.yaml`, the
 * cached `agent_version` hash, and runtime settings (port). Nothing
 * here SSHes to a host or reads filesystems outside the agent's loaded
 * workspace dir; the GH Action that calls this endpoint is the only
 * thing that turns the response into a committed file.
 *
 * Output contract:
 *   - Begins with a generated-by marker so the file's ownership is
 *     unambiguous to humans browsing the agent-workspace repo.
 *   - Stable section ordering so a regen with no underlying changes
 *     produces a byte-identical file (the GH Action skips commit when
 *     `git diff --quiet` is true).
 */
export function renderOperationsDoc(agent: ResolvedAgent): string {
  const settings = getSettings();
  const version = getAgentVersion();
  const sections: string[] = [];

  sections.push(`# Operations: ${agent.name}`);
  sections.push('');
  sections.push(GENERATED_MARKER);
  sections.push('');
  sections.push(
    `**Workspace directory:** \`${agent.dir}\`  ` +
      `\n**Clawndom HTTP port:** \`${settings.port}\`  ` +
      `\n**Service unit:** \`clawndom-${agent.name}.service\`  ` +
      `\n**Logs:** \`/var/log/clawndom-${agent.name}/{clawndom,audit}.log\`  ` +
      `\n**Agent version:** \`${version.hash}\``,
  );
  sections.push('');
  sections.push(renderRepoVersionsSection(version.repos));
  sections.push(renderRoutesSection(agent.config));
  sections.push(renderSchedulesSection(agent.config));
  sections.push(renderRecipesSection(agent.name));

  return (
    sections
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n'
  );
}

export const GENERATED_MARKER =
  '<!-- generated by Clawndom GET /api/agents/:agent/operations.md — do not hand-edit -->';

function renderRepoVersionsSection(
  repos: ReadonlyArray<{ name: string; sha: string; dirty: boolean }>,
): string {
  const rows = ['## Repository versions', ''];
  rows.push('| repo | sha | dirty |');
  rows.push('|---|---|---|');
  for (const repo of repos) {
    const dirtyMark = repo.dirty ? '⚠️ uncommitted changes' : '—';
    rows.push(`| \`${repo.name}\` | \`${repo.sha}\` | ${dirtyMark} |`);
  }
  rows.push('');
  return rows.join('\n');
}

function renderRoutesSection(config: AgentConfig): string {
  const lines = ['## Routes', ''];
  const providers = Object.keys(config.routing)
    .filter((name) => name !== 'schedule')
    .sort();
  if (providers.length === 0) {
    lines.push('_No webhook / event routes._');
    lines.push('');
    return lines.join('\n');
  }
  for (const provider of providers) {
    const rules = config.routing[provider]?.rules ?? [];
    lines.push(`### \`${provider}\``);
    lines.push('');
    if (rules.length === 0) {
      lines.push('_No rules._');
      lines.push('');
      continue;
    }
    for (const rule of rules) {
      lines.push(renderRule(rule));
    }
  }
  return lines.join('\n');
}

function renderRule(rule: AgentRule): string {
  const lines: string[] = [];
  const heading = rule.name ?? rule.id ?? '<unnamed>';
  lines.push(`- **${heading}**`);
  if (rule.messageTemplate !== undefined) {
    lines.push(`  - Template: \`${rule.messageTemplate}\``);
  }
  if (rule.cron !== undefined) {
    lines.push(`  - Cron: \`${rule.cron}\` (${rule.timezone ?? 'UTC'})`);
  }
  const tools = rule.tools ?? [];
  if (tools.length > 0) {
    const refs = tools.map((tool) => `\`${getToolReference(tool)}\``).join(', ');
    lines.push(`  - Tools (${tools.length}): ${refs}`);
  }
  if (rule.dispatches.length > 0) {
    lines.push(`  - Dispatches: ${rule.dispatches.map((d) => `\`${d}\``).join(', ')}`);
  }
  if (rule.session !== undefined) {
    lines.push('  - Session: warm subprocess + Redis-backed resume');
  }
  if (rule.memory?.namespace !== undefined) {
    lines.push(`  - Memory namespace: \`${rule.memory.namespace}\``);
  }
  return lines.join('\n');
}

function renderSchedulesSection(config: AgentConfig): string {
  const lines = ['## Scheduled prompts', ''];
  const scheduleRoute = config.routing['schedule'];
  const rules = scheduleRoute?.rules ?? [];
  if (rules.length === 0) {
    lines.push('_No scheduled prompts declared in `routing.schedule`._');
    lines.push('');
    return lines.join('\n');
  }
  lines.push('| name | cron | timezone | tools | template |');
  lines.push('|---|---|---|---|---|');
  for (const rule of rules) {
    const name = rule.name ?? rule.id ?? '<unnamed>';
    const cron = rule.cron ?? '_(unset)_';
    const tz = rule.timezone ?? 'UTC';
    const toolCount = String(rule.tools?.length ?? 0);
    const template = rule.messageTemplate ?? '_(none)_';
    lines.push(`| \`${name}\` | \`${cron}\` | ${tz} | ${toolCount} | \`${template}\` |`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderRecipesSection(agentName: string): string {
  return [
    '## Common debug recipes',
    '',
    '```bash',
    `# SSH to the host (Tailscale; replace <host> with your tailnet name)`,
    `ssh ubuntu@<host>`,
    '',
    `# Tail clawndom log (NOT journalctl — StandardOutput redirects)`,
    `sudo tail -f /var/log/clawndom-${agentName}/clawndom.log`,
    '',
    `# Tail tool-call audit log`,
    `sudo tail -f /var/log/clawndom-${agentName}/audit.log`,
    '',
    `# Restart the service`,
    `sudo systemctl restart clawndom-${agentName}.service`,
    '',
    `# Inspect the live workspace clone HEAD (often ahead of your local checkout)`,
    `(cd /home/ubuntu/.clawndom-${agentName}/agents/*/ && git log --oneline -5)`,
    '```',
    '',
    '> When debugging "agent says it can\'t do X", check the matching route\'s `tools:` ' +
      'block above. That is the entire source of truth for what this agent can do.',
    '',
  ].join('\n');
}
