import { existsSync, readFileSync } from 'node:fs';
import { hostname } from 'node:os';
import { join } from 'node:path';

import { getSettings } from '../config';
import { getAgentVersion } from './version.service';
import type { ResolvedAgent, AgentConfig, AgentRule } from './agent-loader.service';
import { getToolReference } from './tools/config-schemas';

/**
 * Render a per-agent operations runbook as Markdown. The doc is derived
 * entirely from Clawndom's live state — parsed `clawndom.yaml`, the
 * cached `agent_version` hash, runtime settings (port), the host's
 * tailnet name, and an optional first-paragraph excerpt from
 * `SOUL.md` in the agent's workspace (when present).
 *
 * Output contract:
 *   - Begins with a generated-by marker so the file's ownership is
 *     unambiguous to humans browsing the agent-workspace repo.
 *   - Stable section ordering so a regen with no underlying changes
 *     produces a byte-identical file (the GH Action skips commit when
 *     `git diff --quiet` is true).
 */
export function renderOperationsDoc(agent: ResolvedAgent): string {
  const settings = getSettings();
  const version = getAgentVersion();
  const host = hostname();
  const purpose = readAgentPurpose(agent.dir);
  const sections: string[] = [];

  sections.push(`# Operations: ${agent.name}`);
  sections.push('');
  sections.push(GENERATED_MARKER);
  sections.push('');
  if (purpose !== undefined) {
    sections.push(purpose);
    sections.push('');
  }
  sections.push(
    `**Host:** \`${host}\` (Tailscale; SSH as \`ubuntu@${host}\`)  ` +
      `\n**Workspace directory:** \`${agent.dir}\`  ` +
      `\n**Clawndom HTTP port:** \`${settings.port}\`  ` +
      `\n**Service unit:** \`clawndom-${agent.name}.service\`  ` +
      `\n**Logs:** \`/var/log/clawndom-${agent.name}/{clawndom,audit}.log\`  ` +
      `\n**Agent version:** \`${version.hash}\`  ` +
      `\n**Tool reference catalog:** see [\`AGENCY_TOOLS_CATALOG.md\`](https://github.com/SC0RED/agency-tools/blob/main/AGENCY_TOOLS_CATALOG.md) ` +
      `in agency-tools for each tool's description, args, and secrets.`,
  );
  sections.push('');
  sections.push(renderRepoVersionsSection(version.repos));
  sections.push(renderRoutesSection(agent.config));
  sections.push(renderSchedulesSection(agent.config));
  sections.push(renderRecipesSection(agent.name, host));

  return (
    sections
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n'
  );
}

export const GENERATED_MARKER =
  '<!-- generated by Clawndom GET /api/agents/:agent/operations.md — do not hand-edit -->';

/**
 * Read the first prose paragraph from the workspace's `SOUL.md` to use
 * as a one-line "what is this agent for?" hook. Falls back to
 * `undefined` when the file doesn't exist, is empty, or starts with
 * something other than a prose paragraph (a code fence, a heading
 * with no body, etc.). The renderer just skips the section in those
 * cases — cold-Claude reading the doc still gets the deployment
 * facts, just without the prose intro.
 */
function readAgentPurpose(workspaceDir: string): string | undefined {
  const soulPath = join(workspaceDir, 'SOUL.md');
  if (!existsSync(soulPath)) return undefined;
  const content = readFileSync(soulPath, 'utf-8');
  // Skip leading headings / blank lines; take the first non-empty
  // non-fenced paragraph. Stops at the next blank line or another
  // heading. Caps the excerpt at ~400 chars so a verbose SOUL.md
  // doesn't dominate the doc.
  const paragraph = extractFirstParagraph(content);
  if (paragraph === undefined) return undefined;
  return paragraph.length > 400 ? `${paragraph.slice(0, 397)}...` : paragraph;
}

function extractFirstParagraph(content: string): string | undefined {
  const lines = content.split(/\r?\n/);
  let inFence = false;
  const collected: string[] = [];
  for (const raw of lines) {
    const trimmed = raw.trim();
    if (trimmed.startsWith('```')) {
      inFence = !inFence;
      if (collected.length > 0) break;
      continue;
    }
    if (inFence) continue;
    if (trimmed === '') {
      if (collected.length > 0) break;
      continue;
    }
    if (trimmed.startsWith('#')) {
      if (collected.length > 0) break;
      continue;
    }
    collected.push(trimmed);
  }
  return collected.length === 0 ? undefined : collected.join(' ');
}

function renderRepoVersionsSection(
  repos: ReadonlyArray<{ name: string; sha: string; dirty: boolean }>,
): string {
  const rows = ['## Repository versions', ''];
  rows.push('| repo | sha | dirty |');
  rows.push('|---|---|---|');
  for (const repo of repos) {
    const dirtyMark = repo.dirty ? '⚠️ uncommitted changes' : '—';
    rows.push(`| \`${repo.name}\` | \`${repo.sha}\` | ${dirtyMark} |`);
  }
  rows.push('');
  return rows.join('\n');
}

function renderRoutesSection(config: AgentConfig): string {
  const lines = ['## Routes', ''];
  const providers = Object.keys(config.routing)
    .filter((name) => name !== 'schedule')
    .sort();
  if (providers.length === 0) {
    lines.push('_No webhook / event routes._');
    lines.push('');
    return lines.join('\n');
  }
  for (const provider of providers) {
    const rules = config.routing[provider]?.rules ?? [];
    lines.push(`### \`${provider}\``);
    lines.push('');
    if (rules.length === 0) {
      lines.push('_No rules._');
      lines.push('');
      continue;
    }
    for (const rule of rules) {
      lines.push(renderRule(rule));
    }
  }
  return lines.join('\n');
}

function renderRule(rule: AgentRule): string {
  const lines: string[] = [];
  const heading = rule.name ?? rule.id ?? '<unnamed>';
  lines.push(`- **${heading}**`);
  if (rule.messageTemplate !== undefined) {
    lines.push(`  - Template: \`${rule.messageTemplate}\``);
  }
  if (rule.cron !== undefined) {
    lines.push(`  - Cron: \`${rule.cron}\` (${rule.timezone ?? 'UTC'})`);
  }
  const tools = rule.tools ?? [];
  if (tools.length > 0) {
    const refs = tools.map((tool) => `\`${getToolReference(tool)}\``).join(', ');
    lines.push(`  - Tools (${tools.length}): ${refs}`);
  }
  if (rule.dispatches.length > 0) {
    lines.push(`  - Dispatches: ${rule.dispatches.map((d) => `\`${d}\``).join(', ')}`);
  }
  if (rule.session !== undefined) {
    lines.push('  - Session: warm subprocess + Redis-backed resume');
  }
  if (rule.memory?.namespace !== undefined) {
    lines.push(`  - Memory namespace: \`${rule.memory.namespace}\``);
  }
  return lines.join('\n');
}

function renderSchedulesSection(config: AgentConfig): string {
  const lines = ['## Scheduled prompts', ''];
  const scheduleRoute = config.routing['schedule'];
  const rules = scheduleRoute?.rules ?? [];
  if (rules.length === 0) {
    lines.push('_No scheduled prompts declared in `routing.schedule`._');
    lines.push('');
    return lines.join('\n');
  }
  lines.push('| name | cron | timezone | tools | template |');
  lines.push('|---|---|---|---|---|');
  for (const rule of rules) {
    const name = rule.name ?? rule.id ?? '<unnamed>';
    const cron = rule.cron ?? '_(unset)_';
    const tz = rule.timezone ?? 'UTC';
    const toolCount = String(rule.tools?.length ?? 0);
    const template = rule.messageTemplate ?? '_(none)_';
    lines.push(`| \`${name}\` | \`${cron}\` | ${tz} | ${toolCount} | \`${template}\` |`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderRecipesSection(agentName: string, host: string): string {
  return [
    '## Common debug recipes',
    '',
    '```bash',
    `# SSH to the host (Tailscale)`,
    `ssh ubuntu@${host}`,
    '',
    `# Tail clawndom log (NOT journalctl — StandardOutput redirects)`,
    `sudo tail -f /var/log/clawndom-${agentName}/clawndom.log`,
    '',
    `# Tail tool-call audit log`,
    `sudo tail -f /var/log/clawndom-${agentName}/audit.log`,
    '',
    `# Restart the service`,
    `sudo systemctl restart clawndom-${agentName}.service`,
    '',
    `# Inspect the live workspace clone HEAD (often ahead of your local checkout)`,
    `(cd /home/ubuntu/.clawndom-${agentName}/agents/*/ && git log --oneline -5)`,
    '```',
    '',
    '> When debugging "agent says it can\'t do X", check the matching route\'s `tools:` ' +
      'block above. That is the entire source of truth for what this agent can do.',
    '',
  ].join('\n');
}
